-- SQL to create xlsx_files table similar to lidar_files
-- Run this in Supabase SQL editor or psql connected to your DB
CREATE TABLE IF NOT EXISTS xlsx_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trail_id BIGINT REFERENCES trails(id) ON DELETE SET NULL,
    filename TEXT NOT NULL,
    original_filename TEXT,
    file_url TEXT,
    file_size_mb NUMERIC,
    num_rows INTEGER,
    sheet_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_xlsx_files_trail_id ON xlsx_files(trail_id);
